name: Dart CI

on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # updated from v1 for latest compatibility

      - name: Set up Java (12.x)
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2  # updated for improved caching & stability
        with:
          channel: 'stable'

      - name: Upgrade Flutter packages
        run: flutter pub upgrade --major-versions

      - name: Get Flutter packages
        run: flutter pub get

      - name: Build Debug APK for Appium
        run: flutter build apk --debug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
